### PR TITLE
ML-119 restructure project

### PR DESCRIPTION
**Pull request by Tinggaard**
Make the repo a python package that is installable. 
Resolves issues with the python path and stuff

### CODE REVIEW

**Comment by Tinggaard** [comment]
@askeko would you like to take a look at this, please. Or I will commit sukodu

**Comment by askeko** [comment]
> @askeko would you like to take a look at this, please. Or I will commit sukodu

Yes, certainly. @Tinggaard I will get right on it!

**Comment by askeko** [comment]
I will approve this, however I don't appreciate the extra work this will cause me...

**Review by askeko — APPROVED** [review]
Sigh

**Pull request merged**
